// Centralized query key factory. Import everywhere instead of literal arrays
// so invalidation calls stay in sync with the queries they target.
export const qk = {
  health: ['health'] as const,
  metrics: ['metrics'] as const,
  prometheus: ['prometheus'] as const,
  tasks: ['tasks'] as const,
  task: (id: string) => ['tasks', id] as const,
  workers: ['workers'] as const,
  sessions: ['sessions'] as const,
  sessionsList: (state: string, source: string, search: string) =>
    ['sessions', 'list', state, source, search] as const,
  sessionMessages: (id: string) => ['sessions', id, 'messages'] as const,
  rules: (status?: string) => (status ? (['rules', status] as const) : (['rules'] as const)),
  oracles: ['oracles'] as const,
  sleepCycle: ['sleep-cycle'] as const,
  facts: ['facts'] as const,
  economy: ['economy'] as const,
  approvals: ['approvals'] as const,
  agents: ['agents'] as const,
  agent: (id: string) => ['agents', id] as const,
  skills: (filter?: { kind?: string; agentId?: string; status?: string }) => {
    if (!filter) return ['skills'] as const;
    return ['skills', filter.kind ?? null, filter.agentId ?? null, filter.status ?? null] as const;
  },
  skill: (id: string) => ['skills', 'detail', id] as const,
  patterns: ['patterns'] as const,
  doctor: (deep: boolean) => ['doctor', deep] as const,
  config: ['config'] as const,
  mcp: ['mcp'] as const,
  shadow: (status?: string) => (status ? (['shadow', status] as const) : (['shadow'] as const)),
  traces: (filter: string) => ['traces', filter] as const,
  memory: ['memory'] as const,
  calibration: ['calibration'] as const,
  hms: ['hms'] as const,
  peers: ['peers'] as const,
  providers: ['providers'] as const,
  federation: ['federation'] as const,
  market: ['market'] as const,
  economyRecent: (limit: number) => ['economy', 'recent', limit] as const,
  engine: (id: string) => ['engines', id] as const,
  sessionClarifications: (id: string) => ['sessions', id, 'clarifications'] as const,
  governanceSearch: (filter: string) => ['governance', 'search', filter] as const,
  governanceReplay: (decisionId: string) => ['governance', 'replay', decisionId] as const,
  degradationHealth: ['health', 'degradation'] as const,
};
